---
title: "final"
author: "Lane Whitmore"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
df <- read.csv('2015.csv')
```

```{r}
library(AppliedPredictiveModeling)
library(caret)
bhv.risk <- df
bhv.risk <- bhv.risk[!(is.na(bhv.risk$GENHLTH)),]
set.seed(444)
trainingRows <- createDataPartition(y=bhv.risk$GENHLTH, p=0.75, list = FALSE)
risk.train <- bhv.risk[trainingRows,]
risk.test <- bhv.risk[-trainingRows,]
```

```{r}
library(dplyr)
funcvegamonth <- function(x, na.rm = FALSE) if_else(x>300 & x<400,
                                                    true = x-300, false = if_else(x>200 & x<300,
                                                                                  true=(x-200)*4,
                                                                                  false=if_else(x>100 & x<200,
                                                                                                true=(x-100)*28,
                                                                                                false=if_else(x==300,                                                                                                  true=0,false=if_else(x==555, true=0, false=NaN)))))


## has outlier 2099 lbs
# weight in lbs
funcweight <- function(x, na.rm = FALSE) if_else(x>9000 & x<9999, true = round((x-9000)*2.2),
                                                 false = if_else(x==7777, true = NaN,
                                                                 false = if_else(x==9999,
                                                                                 true = NaN,
                                                                                 false = x)))
# height in inches
funcheight <- function(x, na.rm = FALSE) if_else(x>200 & x <711, 
                                                 true=as.numeric(substr(x,1,1))*12+as.numeric(substr(x,2,3)),
                                                 false = if_else(x > 9000 & x <9999, true= round((x-9000)*0.39370079),
                                                                 false = if_else(x==9999, true = NaN,
                                                                                 false =if_else(x==7777, 
                                                                                                true = NaN, 
                                                                                                false = x))))
# exercise a month
funcexer <- function(x, na.rm = FALSE) if_else(x > 100 & x < 200, true = (x-100)*4,
                                               false = if_else(x > 200 & x < 300, true = x - 200,
                                                               false = if_else(x==777, true = NaN,
                                                                               false = if_else(x==999,
                                                                                               true = NaN, 
                                                                                               false = x))))

# strength training a month
funcstrength <- function(x, na.rm = FALSE) if_else(x>200 & x <300, true = x-200,
                                                   false = if_else(x>100 & x<200,
                                                                   true = (x-100)*4,
                                                                   false = if_else(x==888,
                                                                                   true = 0,
                                                                                   false = if_else(x==777,
                                                                                                   true = NaN,
                                                                                                   false = if_else(x==999,true = NaN, false = x)))))


# Blood sugar checked per year / diabetes foot sores checked per year
funcsgr <- function(x, na.rm = FALSE) if_else(x>400 & x<500, true = x-400,
                                              false = if_else(x>300 & x<400, true = (x-300)*12,
                                                              false = if_else(x>200 & x<300,
                                                                              true = (x-200)*48,
                                                                              false = if_else(x>100 & x<200,
                                                                                              true = (x-100)*336,
                                                                                              false = if_else(x==888,
                                                                                                              true=0,
                                                                                                              false = if_else(x==777, true = NaN, false=if_else(x==999, true = NaN, false = if_else(x==555,true=0,false = x))))))))


# for preds with all values under 76: 88=None, 77 - IDK, 99 = Refused
funcunder76 <- function(x, na.rm = FALSE) if_else(x == 99, true = 0,
                                                   false = if_else(x>0 & x<76,
                                                                   true = x,
                                                                   false = NaN))

# for times
funcidate <- function(x, na.rm = FALSE) as.numeric(substr(x, 3,10))
funcmonthday <- function(x, na.rm = FALSE) as.numeric(substr(x, 3,4))
funcyear<- function(x, na.rm = FALSE) as.numeric(substr(x, 3,6))

# alc days in the last 30
funcalc <- function(x, na.rm = FALSE) if_else(x>100 & x<200, true = (x-100)*4,
                                              false = if_else(x>200 & x<300, true = x-200,
                                                              false = if_else(x==888,true = 0,
                                                                              false = if_else(x==777,
                                                                                              true = NaN,
                                                                                              false = if_else(x==999,
                                                                                                              true = NaN, false = x)))))

funchlth <- function(x, na.rm = FALSE) if_else(x==88, true = 0,false = if_else(x==77,true = NaN,
                                                                               false = if_else(x==99, true = NaN,
                                                                                               false=x)))

funcexhmm <- function(x, na.rm = FALSE) if_else(x==777, 
                                                true = NaN, 
                                                false = if_else(x==999,
                                                                true = NaN,
                                                                false = x))
rounddig0 <- function(x, na.rm = FALSE) round(x, digits=0)

funcchild <- function(x, na.rm = FALSE) if_else(x == 88, true = 0, false = if_else(x==99,
                                                                                   true = NaN,
                                                                                   false = x))
# Want to make a third option that shows all nonresponses whether they be null or refusal
funcbin <- function(x, na.rm = TRUE) if_else(is.na(x), true= 0, 
                                             false = if_else(x== 7 | x== 9,true = 0,
                                                             false = x))
funcmultifact <- function(x, na.rm = TRUE) if_else(is.na(x), true = 0,
                                                   false = if_else(x==77 |x==99,
                                                                   true = 0,
                                                                   false = x))

```

```{r}
bhv.train.fixed <- risk.train %>%
  mutate_at(c(84:89),funcvegamonth)%>%
  mutate_at(65, funcweight)%>%
  mutate_at(66, funcheight)%>%
  mutate_at(c(92,95), funcexer)%>%
  mutate_at(97,funcstrength)%>%
  mutate_at(c(113,114), funcsgr)%>%
  mutate_at(c(81:83,101,115:117,213:220), funcunder76)%>%
  #rounding off columns that need it
  mutate_at(c(17:18,101,272,274,276:287,292:293,295:296,299:300,305:314), rounddig0)%>% 
  # These variables do not impute with median, due to this null + no response + refuse = 
  # 0 representing factorial non-responses all together
  mutate_at(c(35:36,38:39,41,44:45,48,51,60,64,68:77,90,98:100,106:107,110:112,118:120,125,127:128,
              130:136,141:149,151,153,160:174,176:197,211:212,221:222,232,243:244,
              248,255,323:330),funcbin)%>%
  mutate_at(c(63,78,91,94,102:103,105,109,137), funcmultifact)%>%
  # setting necessary variables as factors
  mutate_at(c(1:2,7,10:15,20:25,31:51,53:61,63:64,67:79,90:91,94,98:100,102:103,
              105:107,109:112,118:120,125:149,151,153,158:200,201:212,221:257,
              259,264:271,273,275,288:291,294,297:298,315:330), as.factor)%>%
  mutate_at(3, funcidate)%>%
  mutate_at(c(4:5), funcmonthday)%>%
  mutate_at(6, funcyear)%>%
  mutate_at(80, funcalc)%>%
  mutate_at(93, funcexhmm)%>%
  mutate_at(c(28:30), funchlth)%>%
  mutate_at(62, funcchild)


bhv.test.fixed <- risk.test %>%
  mutate_at(c(84:89),funcvegamonth)%>%
  mutate_at(65, funcweight)%>%
  mutate_at(66, funcheight)%>%
  mutate_at(c(92,95), funcexer)%>%
  mutate_at(97,funcstrength)%>%
  mutate_at(c(113,114), funcsgr)%>%
  mutate_at(c(81:83,101,115:117,213:220), funcunder76)%>%
  mutate_at(c(17:18,101,272,274,276:287,292:293,295:296,299:300,305:314), rounddig0)%>% 
  #rounding off columns that need it
  mutate_at(c(35:36,38:39,41,44:45,48,51,60,64,68:77,90,98:100,106:107,110:112,118:120,125,127:128,
              130:136,141:149,151,153,160:174,176:197,211:212,221:222,232,243:244,
              248,255,323:330),funcbin)%>%
  mutate_at(c(63,78,91,94,102:103,105,109,137), funcmultifact)%>%
  mutate_at(c(1:2,7,10:15,20:25,31:51,53:61,63:64,67:79,90:91,94,98:100,102:103,
              105:107,109:112,118:120,125:149,151,153,158:200,201:212,221:257,
              259,264:271,273,275,288:291,294,297:298,315:330), as.factor)%>%
  mutate_at(3, funcidate)%>%
  mutate_at(c(4:5), funcmonthday)%>%
  mutate_at(6, funcyear)%>%
  mutate_at(80, funcalc)%>%
  mutate_at(93, funcexhmm)%>%
  mutate_at(c(28:30), funchlth)%>%
  mutate_at(62, funcchild)
```


```{r}
degeneratePredictors <- nearZeroVar(bhv.train.fixed)
```


```{r}

bhv.train.nzv <- bhv.train.fixed[,-degeneratePredictors]
bhv.test.nzv <- bhv.test.fixed[,-degeneratePredictors]
# some of the null values can be made into a none classifier
# the assumption being that for things like HIV or Asthma etc.. it simply was not
# Applicable to most people's circumstances

num_cols <- unlist(lapply(bhv.train.nzv, is.numeric))
dub_cols <- unlist(lapply(bhv.train.nzv, is.double))


train.num <- sapply(bhv.train.nzv[,num_cols], function(x) ifelse(is.na(x), median(x, na.rm=TRUE), x))
train.dub <- sapply(bhv.train.nzv[,dub_cols], function(x) ifelse(is.na(x), median(x, na.rm=TRUE), x))

test.num <- sapply(bhv.test.nzv[,num_cols], function(x) ifelse(is.na(x), median(x, na.rm=TRUE), x))
test.dub <- sapply(bhv.test.nzv[,dub_cols], function(x) ifelse(is.na(x), median(x, na.rm=TRUE), x))

bhv.train.nzv[,num_cols] <- train.num
bhv.train.nzv[,dub_cols] <- train.dub

bhv.test.nzv[,num_cols] <- test.num
bhv.test.nzv[,dub_cols] <- test.dub


# Some predictors can be dropped that are full of nulls and not offer any value
# Due to the categorical predictors, correlation can't be used to remove correlated variables
# The variables have been manually removed that are highly related/ measure the same thing
bhv.train.dropped <- bhv.train.nzv[, -c(3,6:10,14:16,46:48,89,93,103:109,119:121,125:134,144:157,181
                                        )]
bhv.test.dropped <- bhv.test.nzv[, -c(3,6:10,14:16,46:48,89,93,103:109,119:121,125:134,144:157,181)]

sapply(bhv.train.dropped, function(x) sum(is.na(x)))
sapply(bhv.train.dropped, function(x) typeof(x))
sum(num_cols)
sum(dub_cols)
```


```{r}
num_colsdr <- unlist(lapply(bhv.train.dropped, is.numeric))
numeric.cor <- cor(bhv.train.dropped[, num_colsdr])
numeric.high <- findCorrelation(bio.cor, cutoff = .85)
bhv.train.cor.nzv <- bhv.train.dropped[, -numeric.high]
bhv.test.cor.nzv <- bhv.test.dropped[, -numeric.high]
```


```{r}

```

```{r}

```

